name: country_db
description: "A new Flutter package project."
version: 1.0.0
homepage:
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0


flutter:
  assets:
    - assets/
