import 'package:countries_db/countries_assets.dart';
import 'package:countries_db/country.dart';

abstract class AppCountries {
  static List<Country> get recommended => [
    for (final country in _all)
      if (!country.isHighRisk) country,
  ];

  static List<Country> get highrisk => [
    for (final country in _all)
      if (country.isHighRisk) country,
  ];

  static final _all = [
    Country(
      name: 'Algeria',
      flagPath: CountryAsset.algeria,
      dialCode: '+213',
      shortCode: 'DZ',
      iso3Code: 'DZA',
      isHighRisk: true,
    ),
    Country(
      name: 'Afghanistan',
      flagPath: CountryAsset.afghanistan,
      dialCode: '+93',
      shortCode: 'AF',
      iso3Code: 'AFG',
    ),
    Country(
      name: 'Aland Islands',
      flagPath: CountryAsset.alandIslands,
      dialCode: '+358',
      shortCode: 'AX',
      iso3Code: 'ALA',
    ),
    Country(
      name: 'Albania',
      flagPath: CountryAsset.albania,
      dialCode: '+355',
      shortCode: 'AL',
      iso3Code: 'ALB',
    ),
    Country(
      name: 'American Samoa',
      flagPath: CountryAsset.americanSamoa,
      dialCode: '+1684',
      shortCode: 'AS',
      iso3Code: 'ASM',
    ),
    Country(
      name: 'Andorra',
      flagPath: CountryAsset.andorra,
      dialCode: '+376',
      shortCode: 'AD',
      iso3Code: 'AND',
    ),
    Country(
      name: 'Angola',
      flagPath: CountryAsset.angola,
      dialCode: '+244',
      shortCode: 'AO',
      iso3Code: 'AGO',
      isHighRisk: true,
    ),
    Country(
      name: 'Anguilla',
      flagPath: CountryAsset.anguilla,
      dialCode: '+1264',
      shortCode: 'AI',
      iso3Code: 'AIA',
    ),
    Country(
      name: 'Antigua And Barbuda',
      flagPath: CountryAsset.antiguaAndBarbuda,
      dialCode: '+1268',
      shortCode: 'AG',
      iso3Code: 'ATG',
    ),
    Country(
      name: 'Argentina',
      flagPath: CountryAsset.argentina,
      dialCode: '+54',
      shortCode: 'AR',
      iso3Code: 'ARG',
    ),
    Country(
      name: 'Armenia',
      flagPath: CountryAsset.armenia,
      dialCode: '+374',
      shortCode: 'AM',
      iso3Code: 'ARM',
    ),
    Country(
      name: 'Aruba',
      flagPath: CountryAsset.aruba,
      dialCode: '+297',
      shortCode: 'AW',
      iso3Code: 'ABW',
    ),
    Country(
      name: 'Australia',
      flagPath: CountryAsset.australia,
      dialCode: '+61',
      shortCode: 'AU',
      iso3Code: 'AUS',
    ),
    Country(
      name: 'Austria',
      flagPath: CountryAsset.austria,
      dialCode: '+43',
      shortCode: 'AT',
      iso3Code: 'AUT',
    ),
    Country(
      name: 'Azerbaijan',
      flagPath: CountryAsset.azerbaijan,
      dialCode: '+994',
      shortCode: 'AZ',
      iso3Code: 'AZE',
    ),
    Country(
      name: 'Bahamas',
      flagPath: CountryAsset.bahamas,
      dialCode: '+1242',
      shortCode: 'BS',
      iso3Code: 'BHS',
    ),
    Country(
      name: 'Bahrain',
      flagPath: CountryAsset.bahrain,
      dialCode: '+973',
      shortCode: 'BH',
      iso3Code: 'BHR',
    ),
    Country(
      name: 'Bangladesh',
      flagPath: CountryAsset.bangladesh,
      dialCode: '+880',
      shortCode: 'BD',
      iso3Code: 'BGD',
    ),
    Country(
      name: 'Barbados',
      flagPath: CountryAsset.barbados,
      dialCode: '+1246',
      shortCode: 'BB',
      iso3Code: 'BRB',
    ),
    Country(
      name: 'Belarus',
      flagPath: CountryAsset.belarus,
      dialCode: '+375',
      shortCode: 'BY',
      iso3Code: 'BLR',
    ),
    Country(
      name: 'Belgium',
      flagPath: CountryAsset.belgium,
      dialCode: '+32',
      shortCode: 'BE',
      iso3Code: 'BEL',
    ),
    Country(
      name: 'Belize',
      flagPath: CountryAsset.belize,
      dialCode: '+501',
      shortCode: 'BZ',
      iso3Code: 'BLZ',
    ),
    Country(
      name: 'Benin',
      flagPath: CountryAsset.benin,
      dialCode: '+229',
      shortCode: 'BJ',
      iso3Code: 'BEN',
    ),
    Country(
      name: 'Bermuda',
      flagPath: CountryAsset.bermuda,
      dialCode: '+1441',
      shortCode: 'BM',
      iso3Code: 'BMU',
    ),
    Country(
      name: 'Bhutan',
      flagPath: CountryAsset.bhutan,
      dialCode: '+975',
      shortCode: 'BT',
      iso3Code: 'BTN',
    ),
    Country(
      name: 'Bolivia',
      flagPath: CountryAsset.bolivia,
      dialCode: '+591',
      shortCode: 'BO',
      iso3Code: 'BOL',
      isHighRisk: true,
    ),
    Country(
      name: 'Bosnia And Herzegovina',
      flagPath: CountryAsset.bosniaAndHerzegovina,
      dialCode: '+387',
      shortCode: 'BA',
      iso3Code: 'BIH',
    ),
    Country(
      name: 'Botswana',
      flagPath: CountryAsset.botswana,
      dialCode: '+267',
      shortCode: 'BW',
      iso3Code: 'BWA',
    ),
    Country(
      name: 'Brazil',
      flagPath: CountryAsset.brazil,
      dialCode: '+55',
      shortCode: 'BR',
      iso3Code: 'BRA',
    ),
    Country(
      name: 'British Indian Ocean Territory',
      flagPath: CountryAsset.britishIndianOceanTerritory,
      dialCode: '+246',
      shortCode: 'IO',
      iso3Code: 'IOT',
    ),
    Country(
      name: 'British Virgin Islands',
      flagPath: CountryAsset.britishVirginIslands,
      dialCode: '+1284',
      shortCode: 'VG',
      iso3Code: 'VGB',
    ),
    Country(
      name: 'Brunei',
      flagPath: CountryAsset.brunei,
      dialCode: '+673',
      shortCode: 'BN',
      iso3Code: 'BRN',
    ),
    Country(
      name: 'Bulgaria',
      flagPath: CountryAsset.bulgaria,
      dialCode: '+359',
      shortCode: 'BG',
      iso3Code: 'BGR',
      isHighRisk: true,
    ),
    Country(
      name: 'Burkina Faso',
      flagPath: CountryAsset.burkinaFaso,
      dialCode: '+226',
      shortCode: 'BF',
      iso3Code: 'BFA',
    ),
    Country(
      name: 'Burundi',
      flagPath: CountryAsset.burundi,
      dialCode: '+257',
      shortCode: 'BI',
      iso3Code: 'BDI',
    ),
    Country(
      name: 'Cambodia',
      flagPath: CountryAsset.cambodia,
      dialCode: '+855',
      shortCode: 'KH',
      iso3Code: 'KHM',
    ),
    Country(
      name: 'Cameroon',
      flagPath: CountryAsset.cameroon,
      dialCode: '+237',
      shortCode: 'CM',
      iso3Code: 'CMR',
      isHighRisk: true,
    ),
    Country(
      name: 'Canada',
      flagPath: CountryAsset.canada,
      dialCode: '+1',
      shortCode: 'CA',
      iso3Code: 'CAN',
    ),
    Country(
      name: 'Cape Verde',
      flagPath: CountryAsset.capeVerde,
      dialCode: '+238',
      shortCode: 'CV',
      iso3Code: 'CPV',
    ),
    Country(
      name: 'Cayman Islands',
      flagPath: CountryAsset.caymanIslands,
      dialCode: '+ 345',
      shortCode: 'KY',
      iso3Code: 'CYM',
    ),
    Country(
      name: 'Central African Republic',
      flagPath: CountryAsset.centralAfricanRepublic,
      dialCode: '+236',
      shortCode: 'CF',
      iso3Code: 'CAF',
    ),
    Country(
      name: 'Chad',
      flagPath: CountryAsset.chad,
      dialCode: '+235',
      shortCode: 'TD',
      iso3Code: 'TCD',
    ),
    Country(
      name: 'Chile',
      flagPath: CountryAsset.chile,
      dialCode: '+56',
      shortCode: 'CL',
      iso3Code: 'CHL',
    ),
    Country(
      name: 'China',
      flagPath: CountryAsset.china,
      dialCode: '+86',
      shortCode: 'CN',
      iso3Code: 'CHN',
    ),
    Country(
      name: 'Colombia',
      flagPath: CountryAsset.colombia,
      dialCode: '+57',
      shortCode: 'CO',
      iso3Code: 'COL',
    ),
    Country(
      name: 'Comoros',
      flagPath: CountryAsset.comoros,
      dialCode: '+269',
      shortCode: 'KM',
      iso3Code: 'COM',
    ),
    Country(
      name: 'Cook Islands',
      flagPath: CountryAsset.cookIslands,
      dialCode: '+682',
      shortCode: 'CK',
      iso3Code: 'COK',
    ),
    Country(
      name: 'Costa Rica',
      flagPath: CountryAsset.costaRica,
      dialCode: '+506',
      shortCode: 'CR',
      iso3Code: 'CRI',
    ),
    Country(
      name: 'Croatia',
      flagPath: CountryAsset.croatia,
      dialCode: '+385',
      shortCode: 'HR',
      iso3Code: 'HRV',
    ),
    Country(
      name: 'Cuba',
      flagPath: CountryAsset.cuba,
      dialCode: '+53',
      shortCode: 'CU',
      iso3Code: 'CUB',
    ),
    Country(
      name: 'Cyprus',
      flagPath: CountryAsset.cyprus,
      dialCode: '+357',
      shortCode: 'CY',
      iso3Code: 'CYP',
    ),
    Country(
      name: 'Czech Republic',
      flagPath: CountryAsset.czechRepublic,
      dialCode: '+420',
      shortCode: 'CZ',
      iso3Code: 'CZE',
    ),
    Country(
      name: 'Democratic Republic Of Congo',
      flagPath: CountryAsset.democraticRepublicOfCongo,
      dialCode: '+243',
      shortCode: 'CD',
      iso3Code: 'COD',
      isHighRisk: true,
    ),
    Country(
      name: 'Denmark',
      flagPath: CountryAsset.denmark,
      dialCode: '+45',
      shortCode: 'DK',
      iso3Code: 'DNK',
    ),
    Country(
      name: 'Djibouti',
      flagPath: CountryAsset.djibouti,
      dialCode: '+253',
      shortCode: 'DJ',
      iso3Code: 'DJI',
    ),
    Country(
      name: 'Dominica',
      flagPath: CountryAsset.dominica,
      dialCode: '+1767',
      shortCode: 'DM',
      iso3Code: 'DMA',
    ),
    Country(
      name: 'Dominican Republic',
      flagPath: CountryAsset.dominicanRepublic,
      dialCode: '+1849',
      shortCode: 'DO',
      iso3Code: 'DOM',
    ),
    Country(
      name: 'East Timor',
      flagPath: CountryAsset.eastTimor,
      dialCode: '+670',
      shortCode: 'TL',
      iso3Code: 'TLS',
    ),
    Country(
      name: 'Ecuador',
      flagPath: CountryAsset.ecuador,
      dialCode: '+593',
      shortCode: 'EC',
      iso3Code: 'ECU',
    ),
    Country(
      name: 'Egypt',
      flagPath: CountryAsset.egypt,
      dialCode: '+20',
      shortCode: 'EG',
      iso3Code: 'EGY',
    ),
    Country(
      name: 'El Salvador',
      flagPath: CountryAsset.elSalvador,
      dialCode: '+503',
      shortCode: 'SV',
      iso3Code: 'SLV',
    ),
    Country(
      name: 'England',
      flagPath: CountryAsset.england,
      dialCode: '+44',
      shortCode: 'GB',
      iso3Code: 'GBR',
    ),
    Country(
      name: 'Equatorial Guinea',
      flagPath: CountryAsset.equatorialGuinea,
      dialCode: '+240',
      shortCode: 'GQ',
      iso3Code: 'GNQ',
    ),
    Country(
      name: 'Eritrea',
      flagPath: CountryAsset.eritrea,
      dialCode: '+291',
      shortCode: 'ER',
      iso3Code: 'ERI',
    ),
    Country(
      name: 'Estonia',
      flagPath: CountryAsset.estonia,
      dialCode: '+372',
      shortCode: 'EE',
      iso3Code: 'EST',
    ),
    Country(
      name: 'Ethiopia',
      flagPath: CountryAsset.ethiopia,
      dialCode: '+251',
      shortCode: 'ET',
      iso3Code: 'ETH',
    ),
    Country(
      name: 'Falkland Islands',
      flagPath: CountryAsset.falklandIslands,
      dialCode: '+500',
      shortCode: 'FK',
      iso3Code: 'FLK',
    ),
    Country(
      name: 'Faroe Islands',
      flagPath: CountryAsset.faroeIslands,
      dialCode: '+298',
      shortCode: 'FO',
      iso3Code: 'FRO',
    ),
    Country(
      name: 'Fiji',
      flagPath: CountryAsset.fiji,
      dialCode: '+679',
      shortCode: 'FJ',
      iso3Code: 'FJI',
    ),
    Country(
      name: 'Finland',
      flagPath: CountryAsset.finland,
      dialCode: '+358',
      shortCode: 'FI',
      iso3Code: 'FIN',
    ),
    Country(
      name: 'France',
      flagPath: CountryAsset.france,
      dialCode: '+33',
      shortCode: 'FR',
      iso3Code: 'FRA',
    ),
    Country(
      name: 'French Polynesia',
      flagPath: CountryAsset.frenchPolynesia,
      dialCode: '+689',
      shortCode: 'PF',
      iso3Code: 'PYF',
    ),
    Country(
      name: 'Gabon',
      flagPath: CountryAsset.gabon,
      dialCode: '+241',
      shortCode: 'GA',
      iso3Code: 'GAB',
    ),
    Country(
      name: 'Gambia',
      flagPath: CountryAsset.gambia,
      dialCode: '+220',
      shortCode: 'GM',
      iso3Code: 'GMB',
    ),
    Country(
      name: 'Georgia',
      flagPath: CountryAsset.georgia,
      dialCode: '+995',
      shortCode: 'GE',
      iso3Code: 'GEO',
    ),
    Country(
      name: 'Germany',
      flagPath: CountryAsset.germany,
      dialCode: '+49',
      shortCode: 'DE',
      iso3Code: 'DEU',
    ),
    Country(
      name: 'Ghana',
      flagPath: CountryAsset.ghana,
      dialCode: '+233',
      shortCode: 'GH',
      iso3Code: 'GHA',
    ),
    Country(
      name: 'Gibraltar',
      flagPath: CountryAsset.gibraltar,
      dialCode: '+350',
      shortCode: 'GI',
      iso3Code: 'GIB',
    ),
    Country(
      name: 'Greece',
      flagPath: CountryAsset.greece,
      dialCode: '+30',
      shortCode: 'GR',
      iso3Code: 'GRC',
    ),
    Country(
      name: 'Greenland',
      flagPath: CountryAsset.greenland,
      dialCode: '+299',
      shortCode: 'GL',
      iso3Code: 'GRL',
    ),
    Country(
      name: 'Grenada',
      flagPath: CountryAsset.grenada,
      dialCode: '+1473',
      shortCode: 'GD',
      iso3Code: 'GRD',
    ),
    Country(
      name: 'Guam',
      flagPath: CountryAsset.guam,
      dialCode: '+1671',
      shortCode: 'GU',
      iso3Code: 'GUM',
    ),
    Country(
      name: 'Guatemala',
      flagPath: CountryAsset.guatemala,
      dialCode: '+502',
      shortCode: 'GT',
      iso3Code: 'GTM',
    ),
    Country(
      name: 'Guernsey',
      flagPath: CountryAsset.guernsey,
      dialCode: '+44',
      shortCode: 'GG',
      iso3Code: 'GGY',
    ),
    Country(
      name: 'Guinea Bissau',
      flagPath: CountryAsset.guineaBissau,
      dialCode: '+245',
      shortCode: 'GW',
      iso3Code: 'GNB',
    ),
    Country(
      name: 'Guinea',
      flagPath: CountryAsset.guinea,
      dialCode: '+224',
      shortCode: 'GN',
      iso3Code: 'GIN',
    ),
    Country(
      name: 'Guyana',
      flagPath: CountryAsset.guyana,
      dialCode: '+595',
      shortCode: 'GY',
      iso3Code: 'GUY',
    ),
    Country(
      name: 'Haiti',
      flagPath: CountryAsset.haiti,
      dialCode: '+509',
      shortCode: 'HT',
      iso3Code: 'HTI',
      isHighRisk: true,
    ),
    Country(
      name: 'Honduras',
      flagPath: CountryAsset.honduras,
      dialCode: '+504',
      shortCode: 'HN',
      iso3Code: 'HND',
    ),
    Country(
      name: 'Hong Kong',
      flagPath: CountryAsset.hongKong,
      dialCode: '+852',
      shortCode: 'HK',
      iso3Code: 'HKG',
    ),
    Country(
      name: 'Hungary',
      flagPath: CountryAsset.hungary,
      dialCode: '+36',
      shortCode: 'HU',
      iso3Code: 'HUN',
    ),
    Country(
      name: 'Iceland',
      flagPath: CountryAsset.iceland,
      dialCode: '+354',
      shortCode: 'IS',
      iso3Code: 'ISL',
    ),
    Country(
      name: 'India',
      flagPath: CountryAsset.india,
      dialCode: '+91',
      shortCode: 'IN',
      iso3Code: 'IND',
    ),
    Country(
      name: 'Indonesia',
      flagPath: CountryAsset.indonesia,
      dialCode: '+62',
      shortCode: 'ID',
      iso3Code: 'IDN',
    ),
    Country(
      name: 'Iran',
      flagPath: CountryAsset.iran,
      dialCode: '+98',
      shortCode: 'IR',
      iso3Code: 'IRN',
    ),
    Country(
      name: 'Iraq',
      flagPath: CountryAsset.iraq,
      dialCode: '+964',
      shortCode: 'IQ',
      iso3Code: 'IRQ',
    ),
    Country(
      name: 'Ireland',
      flagPath: CountryAsset.ireland,
      dialCode: '+353',
      shortCode: 'IE',
      iso3Code: 'IRL',
    ),
    Country(
      name: 'Isle Of Man',
      flagPath: CountryAsset.isleOfMan,
      dialCode: '+44',
      shortCode: 'IM',
      iso3Code: 'IMN',
    ),
    Country(
      name: 'Israel',
      flagPath: CountryAsset.israel,
      dialCode: '+972',
      shortCode: 'IL',
      iso3Code: 'ISR',
    ),
    Country(
      name: 'Italy',
      flagPath: CountryAsset.italy,
      dialCode: '+39',
      shortCode: 'IT',
      iso3Code: 'ITA',
    ),
    Country(
      name: 'Ivory Coast',
      flagPath: CountryAsset.ivoryCoast,
      dialCode: '+225',
      shortCode: 'CI',
      iso3Code: 'CIV',
      isHighRisk: true,
    ),
    Country(
      name: 'Jamaica',
      flagPath: CountryAsset.jamaica,
      dialCode: '+1876',
      shortCode: 'JM',
      iso3Code: 'JAM',
    ),
    Country(
      name: 'Japan',
      flagPath: CountryAsset.japan,
      dialCode: '+81',
      shortCode: 'JP',
      iso3Code: 'JPN',
    ),
    Country(
      name: 'Jersey',
      flagPath: CountryAsset.jersey,
      dialCode: '+44',
      shortCode: 'JE',
      iso3Code: 'JEY',
    ),
    Country(
      name: 'Jordan',
      flagPath: CountryAsset.jordan,
      dialCode: '+962',
      shortCode: 'JO',
      iso3Code: 'JOR',
    ),
    Country(
      name: 'Kazakhstan',
      flagPath: CountryAsset.kazakhstan,
      dialCode: '+77',
      shortCode: 'KZ',
      iso3Code: 'KAZ',
    ),
    Country(
      name: 'Kenya',
      flagPath: CountryAsset.kenya,
      dialCode: '+254',
      shortCode: 'KE',
      iso3Code: 'KEN',
      isHighRisk: true,
    ),
    Country(
      name: 'Kiribati',
      flagPath: CountryAsset.kiribati,
      dialCode: '+686',
      shortCode: 'KI',
      iso3Code: 'KIR',
    ),
    Country(
      name: 'Kosovo',
      flagPath: CountryAsset.kosovo,
      dialCode: '+383',
      shortCode: 'XK',
      iso3Code: 'XKO',
    ),
    Country(
      name: 'Kuwait',
      flagPath: CountryAsset.kuwait,
      dialCode: '+965',
      shortCode: 'KW',
      iso3Code: 'KWT',
      isHighRisk: true,
    ),
    Country(
      name: 'Kyrgyzstan',
      flagPath: CountryAsset.kyrgyzstan,
      dialCode: '+996',
      shortCode: 'KG',
      iso3Code: 'KGZ',
    ),
    Country(
      name: 'Laos',
      flagPath: CountryAsset.laos,
      dialCode: '+856',
      shortCode: 'LA',
      iso3Code: 'LAO',
      isHighRisk: true,
    ),
    Country(
      name: 'Latvia',
      flagPath: CountryAsset.latvia,
      dialCode: '+371',
      shortCode: 'LV',
      iso3Code: 'LVA',
    ),
    Country(
      name: 'Lebanon',
      flagPath: CountryAsset.lebanon,
      dialCode: '+961',
      shortCode: 'LB',
      iso3Code: 'LBN',
      isHighRisk: true,
    ),
    Country(
      name: 'Lesotho',
      flagPath: CountryAsset.lesotho,
      dialCode: '+266',
      shortCode: 'LS',
      iso3Code: 'LSO',
    ),
    Country(
      name: 'Liberia',
      flagPath: CountryAsset.liberia,
      dialCode: '+231',
      shortCode: 'LR',
      iso3Code: 'LBR',
    ),
    Country(
      name: 'Libya',
      flagPath: CountryAsset.libya,
      dialCode: '+218',
      shortCode: 'LY',
      iso3Code: 'LBY',
    ),
    Country(
      name: 'Liechtenstein',
      flagPath: CountryAsset.liechtenstein,
      dialCode: '+423',
      shortCode: 'LI',
      iso3Code: 'LIE',
    ),
    Country(
      name: 'Lithuania',
      flagPath: CountryAsset.lithuania,
      dialCode: '+370',
      shortCode: 'LT',
      iso3Code: 'LTU',
    ),
    Country(
      name: 'Luxembourg',
      flagPath: CountryAsset.luxembourg,
      dialCode: '+352',
      shortCode: 'LU',
      iso3Code: 'LUX',
    ),
    Country(
      name: 'Macao',
      flagPath: CountryAsset.macao,
      dialCode: '+853',
      shortCode: 'MO',
      iso3Code: 'MAC',
    ),
    Country(
      name: 'Madagascar',
      flagPath: CountryAsset.madagascar,
      dialCode: '+261',
      shortCode: 'MG',
      iso3Code: 'MDG',
    ),
    Country(
      name: 'Malawi',
      flagPath: CountryAsset.malawi,
      dialCode: '+265',
      shortCode: 'MW',
      iso3Code: 'MWI',
    ),
    Country(
      name: 'Malaysia',
      flagPath: CountryAsset.malaysia,
      dialCode: '+60',
      shortCode: 'MY',
      iso3Code: 'MYS',
    ),
    Country(
      name: 'Maldives',
      flagPath: CountryAsset.maldives,
      dialCode: '+960',
      shortCode: 'MV',
      iso3Code: 'MDV',
    ),
    Country(
      name: 'Mali',
      flagPath: CountryAsset.mali,
      dialCode: '+223',
      shortCode: 'ML',
      iso3Code: 'MLI',
    ),
    Country(
      name: 'Malta',
      flagPath: CountryAsset.malta,
      dialCode: '+356',
      shortCode: 'MT',
      iso3Code: 'MLT',
    ),
    Country(
      name: 'Marshall Island',
      flagPath: CountryAsset.marshallIsland,
      dialCode: '+692',
      shortCode: 'MH',
      iso3Code: 'MHL',
    ),
    Country(
      name: 'Martinique',
      flagPath: CountryAsset.martinique,
      dialCode: '+596',
      shortCode: 'MQ',
      iso3Code: 'MTQ',
    ),
    Country(
      name: 'Mauritania',
      flagPath: CountryAsset.mauritania,
      dialCode: '+222',
      shortCode: 'MR',
      iso3Code: 'MRT',
    ),
    Country(
      name: 'Mauritius',
      flagPath: CountryAsset.mauritius,
      dialCode: '+230',
      shortCode: 'MU',
      iso3Code: 'MUS',
    ),
    Country(
      name: 'Mexico',
      flagPath: CountryAsset.mexico,
      dialCode: '+52',
      shortCode: 'MX',
      iso3Code: 'MEX',
    ),
    Country(
      name: 'Micronesia',
      flagPath: CountryAsset.micronesia,
      dialCode: '+691',
      shortCode: 'FM',
      iso3Code: 'FSM',
    ),
    Country(
      name: 'Moldova',
      flagPath: CountryAsset.moldova,
      dialCode: '+373',
      shortCode: 'MD',
      iso3Code: 'MDA',
    ),
    Country(
      name: 'Monaco',
      flagPath: CountryAsset.monaco,
      dialCode: '+377',
      shortCode: 'MC',
      iso3Code: 'MCO',
      isHighRisk: true,
    ),
    Country(
      name: 'Mongolia',
      flagPath: CountryAsset.mongolia,
      dialCode: '+976',
      shortCode: 'MN',
      iso3Code: 'MNG',
    ),
    Country(
      name: 'Montenegro',
      flagPath: CountryAsset.montenegro,
      dialCode: '+382',
      shortCode: 'ME',
      iso3Code: 'MNE',
    ),
    Country(
      name: 'Montserrat',
      flagPath: CountryAsset.montserrat,
      dialCode: '+1664',
      shortCode: 'MS',
      iso3Code: 'MSR',
    ),
    Country(
      name: 'Morocco',
      flagPath: CountryAsset.morocco,
      dialCode: '+212',
      shortCode: 'MA',
      iso3Code: 'MAR',
    ),
    Country(
      name: 'Mozambique',
      flagPath: CountryAsset.mozambique,
      dialCode: '+258',
      shortCode: 'MZ',
      iso3Code: 'MOZ',
    ),
    Country(
      name: 'Myanmar',
      flagPath: CountryAsset.myanmar,
      dialCode: '+95',
      shortCode: 'MM',
      iso3Code: 'MMR',
    ),
    Country(
      name: 'Namibia',
      flagPath: CountryAsset.namibia,
      dialCode: '+264',
      shortCode: 'NA',
      iso3Code: 'NAM',
      isHighRisk: true,
    ),
    Country(
      name: 'Nauru',
      flagPath: CountryAsset.nauru,
      dialCode: '+674',
      shortCode: 'NR',
      iso3Code: 'NRU',
    ),
    Country(
      name: 'Nepal',
      flagPath: CountryAsset.nepal,
      dialCode: '+977',
      shortCode: 'NP',
      iso3Code: 'NPL',
      isHighRisk: true,
    ),
    Country(
      name: 'Netherlands',
      flagPath: CountryAsset.netherlands,
      dialCode: '+31',
      shortCode: 'NL',
      iso3Code: 'NLD',
    ),
    Country(
      name: 'New Zealand',
      flagPath: CountryAsset.newZealand,
      dialCode: '+64',
      shortCode: 'NZ',
      iso3Code: 'NZL',
    ),
    Country(
      name: 'Nicaragua',
      flagPath: CountryAsset.nicaragua,
      dialCode: '+505',
      shortCode: 'NI',
      iso3Code: 'NIC',
    ),
    Country(
      name: 'Niger',
      flagPath: CountryAsset.niger,
      dialCode: '+227',
      shortCode: 'NE',
      iso3Code: 'NER',
    ),
    Country(
      name: 'Nigeria',
      flagPath: CountryAsset.nigeria,
      dialCode: '+234',
      shortCode: 'NG',
      iso3Code: 'NGA',
    ),
    Country(
      name: 'Niue',
      flagPath: CountryAsset.niue,
      dialCode: '+683',
      shortCode: 'NU',
      iso3Code: 'NIU',
    ),
    Country(
      name: 'Norfolk Island',
      flagPath: CountryAsset.norfolkIsland,
      dialCode: '+672',
      shortCode: 'NF',
      iso3Code: 'NFK',
    ),
    Country(
      name: 'North Korea',
      flagPath: CountryAsset.northKorea,
      dialCode: '+850',
      shortCode: 'KP',
      iso3Code: 'PRK',
    ),
    Country(
      name: 'Northern Marianas Islands',
      flagPath: CountryAsset.northernMarianasIslands,
      dialCode: '+1670',
      shortCode: 'MP',
      iso3Code: 'MNP',
    ),
    Country(
      name: 'Norway',
      flagPath: CountryAsset.norway,
      dialCode: '+47',
      shortCode: 'NO',
      iso3Code: 'NOR',
    ),
    Country(
      name: 'Oman',
      flagPath: CountryAsset.oman,
      dialCode: '+968',
      shortCode: 'OM',
      iso3Code: 'OMN',
    ),
    Country(
      name: 'Pakistan',
      flagPath: CountryAsset.pakistan,
      dialCode: '+92',
      shortCode: 'PK',
      iso3Code: 'PAK',
    ),
    Country(
      name: 'Palau',
      flagPath: CountryAsset.palau,
      dialCode: '+680',
      shortCode: 'PW',
      iso3Code: 'PLW',
    ),
    Country(
      name: 'Palestine',
      flagPath: CountryAsset.palestine,
      dialCode: '+970',
      shortCode: 'PS',
      iso3Code: 'PSE',
    ),
    Country(
      name: 'Panama',
      flagPath: CountryAsset.panama,
      dialCode: '+507',
      shortCode: 'PA',
      iso3Code: 'PAN',
    ),
    Country(
      name: 'Papua New Guinea',
      flagPath: CountryAsset.papuaNewGuinea,
      dialCode: '+675',
      shortCode: 'PG',
      iso3Code: 'PNG',
      isHighRisk: true,
    ),
    Country(
      name: 'Paraguay',
      flagPath: CountryAsset.paraguay,
      dialCode: '+595',
      shortCode: 'PY',
      iso3Code: 'PRY',
    ),
    Country(
      name: 'Peru',
      flagPath: CountryAsset.peru,
      dialCode: '+51',
      shortCode: 'PE',
      iso3Code: 'PER',
    ),
    Country(
      name: 'Philippines',
      flagPath: CountryAsset.philippines,
      dialCode: '+63',
      shortCode: 'PH',
      iso3Code: 'PHL',
    ),
    Country(
      name: 'Pitcairn Islands',
      flagPath: CountryAsset.pitcairnIslands,
      dialCode: '+872',
      shortCode: 'PN',
      iso3Code: 'PCN',
    ),
    Country(
      name: 'Poland',
      flagPath: CountryAsset.poland,
      dialCode: '+48',
      shortCode: 'PL',
      iso3Code: 'POL',
    ),
    Country(
      name: 'Portugal',
      flagPath: CountryAsset.portugal,
      dialCode: '+351',
      shortCode: 'PT',
      iso3Code: 'PRT',
    ),
    Country(
      name: 'Puerto Rico',
      flagPath: CountryAsset.puertoRico,
      dialCode: '+1939',
      shortCode: 'PR',
      iso3Code: 'PRI',
    ),
    Country(
      name: 'Qatar',
      flagPath: CountryAsset.qatar,
      dialCode: '+974',
      shortCode: 'QA',
      iso3Code: 'QAT',
    ),
    Country(
      name: 'Republic Of Macedonia',
      flagPath: CountryAsset.republicOfMacedonia,
      dialCode: '+389',
      shortCode: 'MK',
      iso3Code: 'MKD',
    ),
    Country(
      name: 'Republic Of The Congo',
      flagPath: CountryAsset.republicOfTheCongo,
      dialCode: '+242',
      shortCode: 'CG',
      iso3Code: 'COG',
    ),
    Country(
      name: 'Romania',
      flagPath: CountryAsset.romania,
      dialCode: '+40',
      shortCode: 'RO',
      iso3Code: 'ROU',
    ),
    Country(
      name: 'Russia',
      flagPath: CountryAsset.russia,
      dialCode: '+7',
      shortCode: 'RU',
      iso3Code: 'RUS',
    ),
    Country(
      name: 'Rwanda',
      flagPath: CountryAsset.rwanda,
      dialCode: '+250',
      shortCode: 'RW',
      iso3Code: 'RWA',
    ),
    Country(
      name: 'Samoa',
      flagPath: CountryAsset.samoa,
      dialCode: '+685',
      shortCode: 'WS',
      iso3Code: 'WSM',
    ),
    Country(
      name: 'San Marino',
      flagPath: CountryAsset.sanMarino,
      dialCode: '+378',
      shortCode: 'SM',
      iso3Code: 'SMR',
    ),
    Country(
      name: 'Sao Tome And Prince',
      flagPath: CountryAsset.saoTomeAndPrince,
      dialCode: '+239',
      shortCode: 'ST',
      iso3Code: 'STP',
    ),
    Country(
      name: 'Saudi Arabia',
      flagPath: CountryAsset.saudiArabia,
      dialCode: '+966',
      shortCode: 'SA',
      iso3Code: 'SAU',
    ),
    Country(
      name: 'Scotland',
      flagPath: CountryAsset.scotland,
      dialCode: '+44',
      shortCode: 'GB',
      iso3Code: 'GBR',
    ),
    Country(
      name: 'Senegal',
      flagPath: CountryAsset.senegal,
      dialCode: '+221',
      shortCode: 'SN',
      iso3Code: 'SEN',
    ),
    Country(
      name: 'Serbia',
      flagPath: CountryAsset.serbia,
      dialCode: '+381',
      shortCode: 'RS',
      iso3Code: 'SRB',
    ),
    Country(
      name: 'Seychelles',
      flagPath: CountryAsset.seychelles,
      dialCode: '+248',
      shortCode: 'SC',
      iso3Code: 'SYC',
    ),
    Country(
      name: 'Sierra Leone',
      flagPath: CountryAsset.sierraLeone,
      dialCode: '+232',
      shortCode: 'SL',
      iso3Code: 'SLE',
    ),
    Country(
      name: 'Singapore',
      flagPath: CountryAsset.singapore,
      dialCode: '+65',
      shortCode: 'SG',
      iso3Code: 'SGP',
    ),
    Country(
      name: 'Slovakia',
      flagPath: CountryAsset.slovakia,
      dialCode: '+421',
      shortCode: 'SK',
      iso3Code: 'SVK',
    ),
    Country(
      name: 'Slovenia',
      flagPath: CountryAsset.slovenia,
      dialCode: '+386',
      shortCode: 'SI',
      iso3Code: 'SVN',
    ),
    Country(
      name: 'Solomon Islands',
      flagPath: CountryAsset.solomonIslands,
      dialCode: '+677',
      shortCode: 'SB',
      iso3Code: 'SLB',
    ),
    Country(
      name: 'Somalia',
      flagPath: CountryAsset.somalia,
      dialCode: '+252',
      shortCode: 'SO',
      iso3Code: 'SOM',
    ),
    Country(
      name: 'South Africa',
      flagPath: CountryAsset.southAfrica,
      dialCode: '+27',
      shortCode: 'ZA',
      iso3Code: 'ZAF',
    ),
    Country(
      name: 'South Korea',
      flagPath: CountryAsset.southKorea,
      dialCode: '+82',
      shortCode: 'KR',
      iso3Code: 'KOR',
    ),
    Country(
      name: 'South Sudan',
      flagPath: CountryAsset.southSudan,
      dialCode: '+211',
      shortCode: 'SS',
      iso3Code: 'SSD',
      isHighRisk: true,
    ),
    Country(
      name: 'Spain',
      flagPath: CountryAsset.spain,
      dialCode: '+34',
      shortCode: 'ES',
      iso3Code: 'ESP',
    ),
    Country(
      name: 'Sri Lanka',
      flagPath: CountryAsset.sriLanka,
      dialCode: '+94',
      shortCode: 'LK',
      iso3Code: 'LKA',
    ),
    Country(
      name: 'St Barts',
      flagPath: CountryAsset.stBarts,
      dialCode: '+590',
      shortCode: 'BL',
      iso3Code: 'BLM',
    ),
    Country(
      name: 'St Lucia',
      flagPath: CountryAsset.stLucia,
      dialCode: '+1758',
      shortCode: 'LC',
      iso3Code: 'LCA',
    ),
    Country(
      name: 'St Vincent And The Grenadines',
      flagPath: CountryAsset.stVincentAndTheGrenadines,
      dialCode: '+1784',
      shortCode: 'VC',
      iso3Code: 'VCT',
    ),
    Country(
      name: 'Sudan',
      flagPath: CountryAsset.sudan,
      dialCode: '+249',
      shortCode: 'SD',
      iso3Code: 'SDN',
    ),
    Country(
      name: 'Suriname',
      flagPath: CountryAsset.suriname,
      dialCode: '+597',
      shortCode: 'SR',
      iso3Code: 'SUR',
    ),
    Country(
      name: 'Swaziland',
      flagPath: CountryAsset.swaziland,
      dialCode: '+268',
      shortCode: 'SZ',
      iso3Code: 'SWZ',
    ),
    Country(
      name: 'Sweden',
      flagPath: CountryAsset.sweden,
      dialCode: '+46',
      shortCode: 'SE',
      iso3Code: 'SWE',
    ),
    Country(
      name: 'Switzerland',
      flagPath: CountryAsset.switzerland,
      dialCode: '+41',
      shortCode: 'CH',
      iso3Code: 'CHE',
    ),
    Country(
      name: 'Syria',
      flagPath: CountryAsset.syria,
      dialCode: '+963',
      shortCode: 'SY',
      iso3Code: 'SYR',
      isHighRisk: true,
    ),
    Country(
      name: 'Taiwan',
      flagPath: CountryAsset.taiwan,
      dialCode: '+886',
      shortCode: 'TW',
      iso3Code: 'TWN',
    ),
    Country(
      name: 'Tajikistan',
      flagPath: CountryAsset.tajikistan,
      dialCode: '+992',
      shortCode: 'TJ',
      iso3Code: 'TJK',
    ),
    Country(
      name: 'Tanzania',
      flagPath: CountryAsset.tanzania,
      dialCode: '+255',
      shortCode: 'TZ',
      iso3Code: 'TZA',
    ),
    Country(
      name: 'Thailand',
      flagPath: CountryAsset.thailand,
      dialCode: '+66',
      shortCode: 'TH',
      iso3Code: 'THA',
    ),
    Country(
      name: 'Togo',
      flagPath: CountryAsset.togo,
      dialCode: '+228',
      shortCode: 'TG',
      iso3Code: 'TGO',
    ),
    Country(
      name: 'Tokelau',
      flagPath: CountryAsset.tokelau,
      dialCode: '+690',
      shortCode: 'TK',
      iso3Code: 'TKL',
    ),
    Country(
      name: 'Tonga',
      flagPath: CountryAsset.tonga,
      dialCode: '+676',
      shortCode: 'TO',
      iso3Code: 'TON',
    ),
    Country(
      name: 'Trinidad And Tobago',
      flagPath: CountryAsset.trinidadAndTobago,
      dialCode: '+1868',
      shortCode: 'TT',
      iso3Code: 'TTO',
    ),
    Country(
      name: 'Tunisia',
      flagPath: CountryAsset.tunisia,
      dialCode: '+216',
      shortCode: 'TN',
      iso3Code: 'TUN',
    ),
    Country(
      name: 'Turkey',
      flagPath: CountryAsset.turkey,
      dialCode: '+90',
      shortCode: 'TR',
      iso3Code: 'TUR',
    ),
    Country(
      name: 'Turkmenistan',
      flagPath: CountryAsset.turkmenistan,
      dialCode: '+993',
      shortCode: 'TM',
      iso3Code: 'TKM',
    ),
    Country(
      name: 'Turks And Caicos',
      flagPath: CountryAsset.turksAndCaicos,
      dialCode: '+1649',
      shortCode: 'TC',
      iso3Code: 'TCA',
    ),
    Country(
      name: 'Tuvalu',
      flagPath: CountryAsset.tuvalu,
      dialCode: '+688',
      shortCode: 'TV',
      iso3Code: 'TUV',
    ),
    Country(
      name: 'Uganda',
      flagPath: CountryAsset.uganda,
      dialCode: '+256',
      shortCode: 'UG',
      iso3Code: 'UGA',
    ),
    Country(
      name: 'Ukraine',
      flagPath: CountryAsset.ukraine,
      dialCode: '+380',
      shortCode: 'UA',
      iso3Code: 'UKR',
    ),
    Country(
      name: 'United Arab Emirates',
      flagPath: CountryAsset.unitedArabEmirates,
      dialCode: '+971',
      shortCode: 'AE',
      iso3Code: 'ARE',
    ),
    Country(
      name: 'United Kingdom',
      flagPath: CountryAsset.unitedKingdom,
      dialCode: '+44',
      shortCode: 'GB',
      iso3Code: 'GBR',
    ),
    Country(
      name: 'United States',
      flagPath: CountryAsset.unitedStates,
      dialCode: '+1',
      shortCode: 'US',
      iso3Code: 'USA',
    ),
    Country(
      name: 'Uruguay',
      flagPath: CountryAsset.uruguay,
      dialCode: '+598',
      shortCode: 'UY',
      iso3Code: 'URY',
    ),
    Country(
      name: 'Uzbekistan',
      flagPath: CountryAsset.uzbekistan,
      dialCode: '+998',
      shortCode: 'UZ',
      iso3Code: 'UZB',
    ),
    Country(
      name: 'Vanuatu',
      flagPath: CountryAsset.vanuatu,
      dialCode: '+678',
      shortCode: 'VU',
      iso3Code: 'VUT',
    ),
    Country(
      name: 'Vatican City',
      flagPath: CountryAsset.vaticanCity,
      dialCode: '+379',
      shortCode: 'VA',
      iso3Code: 'VAT',
    ),
    Country(
      name: 'Venezuela',
      flagPath: CountryAsset.venezuela,
      dialCode: '+58',
      shortCode: 'VE',
      iso3Code: 'VEN',
      isHighRisk: true,
    ),
    Country(
      name: 'Vietnam',
      flagPath: CountryAsset.vietnam,
      dialCode: '+84',
      shortCode: 'VN',
      iso3Code: 'VNM',
      isHighRisk: true,
    ),
    Country(
      name: 'Virgin Islands',
      flagPath: CountryAsset.virginIslands,
      dialCode: '+1340',
      shortCode: 'VI',
      iso3Code: 'VIR',
      isHighRisk: true,
    ),
    Country(
      name: 'Wales',
      flagPath: CountryAsset.wales,
      dialCode: '+44',
      shortCode: 'GB',
      iso3Code: 'GBR',
    ),
    Country(
      name: 'Yemen',
      flagPath: CountryAsset.yemen,
      dialCode: '+967',
      shortCode: 'YE',
      iso3Code: 'YEM',
      isHighRisk: true,
    ),
    Country(
      name: 'Zambia',
      flagPath: CountryAsset.zambia,
      dialCode: '+260',
      shortCode: 'ZM',
      iso3Code: 'ZMB',
    ),
    Country(
      name: 'Zimbabwe',
      flagPath: CountryAsset.zimbabwe,
      dialCode: '+263',
      shortCode: 'ZW',
      iso3Code: 'ZWE',
    ),
  ];
}
